apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microservices-reader
  namespace: platform-system
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-reader-binding
  namespace: platform-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: microservices-reader
subjects:
- kind: ServiceAccount
  name: frontend-serviceaccount
  namespace: platform-system
